import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
//import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const headersList = headers();
  // const host = headersList.get("host");
  return (
    <html
      lang="en"
      className="h-full w-full"
    >
      <body className={cn(inter.className, "antialiased h-screen pt-20")}>
        <Navbar />
        <div className="container mx-auto h-screen">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
